/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.2
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using Telerik.Sitefinity.Model;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Security;
using Telerik.Sitefinity.Security.Claims;
using Telerik.Sitefinity.Security.Model;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "OpenEdgeCustomerOrders_MVC", Title = "OpenEdgeCustomerOrders", SectionName = "CustomWidgets")]
	public class OpenEdgeCustomerOrdersController : Controller
	{
		// GET: OpenEdgeCustomerOrders
		public ActionResult Index()
		{
			var model = new OpenEdgeCustomerOrdersModel();
			model.OpenEdgeOrderApi = this.OrderApi;
			model.OpenEdgeOrderItemApi = this.OrderItemApi;
			model.CustomerNumber = GetUserCustomerNumber();

			return View(model);
		}

		private decimal GetUserCustomerNumber()
		{
			var currentUserId = GetCurrentUserId();
			return CurrentUserCustomerNumber(currentUserId);
		}

		private decimal CurrentUserCustomerNumber(Guid userId)
		{
			if (userId != null && userId != Guid.Empty)
			{
				UserProfileManager profileManager = UserProfileManager.GetManager();

				var profile = profileManager.GetUserProfile(userId, "Telerik.Sitefinity.Security.Model.OpenEdgeFields");
				if (profile != null)
				{
					return profile.GetValue<decimal>("CustomerNumber");
				}
			}
			return 0;
		}

		private Guid GetCurrentUserId()
		{
			var identity = ClaimsManager.GetCurrentIdentity();

			var userName = identity.Name;
			return identity.UserId;
		}

		public string OrderApi { get; set; }
		public string OrderItemApi { get; set; }
	}
}