/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.2
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using System;
using System.Web.Mvc;
using Telerik.Sitefinity.Libraries.Model;
using Telerik.Sitefinity.Mvc;
using Newtonsoft.Json;
using Telerik.Sitefinity.Modules.Libraries;
using System.Linq;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "UserFileViewer_MVC", Title = "User File Viewer", SectionName = "ContentToolboxSection", CssClass="sfDownloadListIcn sfMvcIcn")]
	public class UserFileViewerController : Controller
	{
		public string SelectedLibraryId { get; set; }
		public string SelectedLibrary { get; set; }
		public string ProviderName { get { return providerName; } set { providerName = value; } }
		// GET: UserFileViewer
		public ActionResult Index()
		{
			var model = new UserFileViewerModel();
			if (!SelectedLibraryId.IsNullOrWhitespace())
			{
				model.SelectedLibraryId = Guid.Parse(SelectedLibraryId);
				model.SelectedLibrary = LibrariesManager.GetManager().GetDocumentLibraries().FirstOrDefault(l => l.Id == model.SelectedLibraryId);
			}
	
			model.ProviderName = ProviderName;
			return View(model);
		}

		private string providerName = "OpenAccessDataProvider";
	}
}