/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.2
</auto-generated>
------------------------------------------------------------------------------ */

using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SitefinityWebApp.Mvc.Models
{
	public class OpenEdgeCustomerOrdersModel
	{
		public decimal CustomerNumber { get; set; }
		public string OpenEdgeOrderApi { get; set; }
		public string OpenEdgeOrderItemApi { get; set; }
	}
}