/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.2
</auto-generated>
------------------------------------------------------------------------------ */

using System;
using System.Web.Mvc;
using Telerik.Sitefinity.Libraries.Model;
using Telerik.Sitefinity.Mvc;

namespace SitefinityWebApp.Mvc.Models
{
	public class UserFileViewerModel
	{
		public Guid SelectedLibraryId { get; set; }
		public Library SelectedLibrary { get; set; }
		public string ProviderName { get; set; }
	}
}